### ISSUE TITLE
Walls import doesn't work with Foundry 0.6.2

### ISSUE THREAD

**Issue by kunxin-chor** [moo-man/FVTT-DD-Import#13] opened 2020-06-03 05:07 UTC
The map image is imported, but no walls or windows are imported.

**Comment by moo-man** [comment] 2020-06-03 05:14
Are you a fortune teller? 👀 

Do you mean 0.6.1? Regardless, I cannot reproduce. Perhaps send me your dd2vtt file or dungeondraft file

**Comment by kunxin-chor** [comment] 2020-06-08 14:24
Hi, thanks for taking a look at the file. You can find it here: https://drive.google.com/file/d/1tghecRMJ91rSHCCwAnOmWOh-zHslt7Ag/view?usp=sharing

**Comment by moo-man** [comment] 2020-06-08 15:35
![image](https://user-images.githubusercontent.com/28637157/84050726-bc144680-a973-11ea-9a14-90b653a18fac.png)
Works fine for me, can you describe your process?

**Comment by moo-man** [comment] 2020-07-18 19:50
Closing this due to lack of info. @kunxin-chor if you have more details please comment or reopen if necessary.

**Closed by moo-man** 2020-07-18 19:50 UTC
